package com.jundger.work.pojo;

public class OrderNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_notify.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_notify.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_notify.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_notify.repairman_id
     *
     * @mbggenerated
     */
    private Integer repairmanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_notify.repaiaman_phone
     *
     * @mbggenerated
     */
    private String repaiamanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_notify.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_notify
     *
     * @mbggenerated
     */
    public OrderNotify(Integer id, Integer orderId, String orderNo, Integer repairmanId, String repaiamanPhone, String flag) {
        this.id = id;
        this.orderId = orderId;
        this.orderNo = orderNo;
        this.repairmanId = repairmanId;
        this.repaiamanPhone = repaiamanPhone;
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_notify
     *
     * @mbggenerated
     */
    public OrderNotify() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_notify.id
     *
     * @return the value of order_notify.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_notify.id
     *
     * @param id the value for order_notify.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_notify.order_id
     *
     * @return the value of order_notify.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_notify.order_id
     *
     * @param orderId the value for order_notify.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_notify.order_no
     *
     * @return the value of order_notify.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_notify.order_no
     *
     * @param orderNo the value for order_notify.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_notify.repairman_id
     *
     * @return the value of order_notify.repairman_id
     *
     * @mbggenerated
     */
    public Integer getRepairmanId() {
        return repairmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_notify.repairman_id
     *
     * @param repairmanId the value for order_notify.repairman_id
     *
     * @mbggenerated
     */
    public void setRepairmanId(Integer repairmanId) {
        this.repairmanId = repairmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_notify.repaiaman_phone
     *
     * @return the value of order_notify.repaiaman_phone
     *
     * @mbggenerated
     */
    public String getRepaiamanPhone() {
        return repaiamanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_notify.repaiaman_phone
     *
     * @param repaiamanPhone the value for order_notify.repaiaman_phone
     *
     * @mbggenerated
     */
    public void setRepaiamanPhone(String repaiamanPhone) {
        this.repaiamanPhone = repaiamanPhone == null ? null : repaiamanPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_notify.flag
     *
     * @return the value of order_notify.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_notify.flag
     *
     * @param flag the value for order_notify.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }
}