package com.jundger.work.pojo;

public class OrderCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_code.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_code.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_code.code_id
     *
     * @mbggenerated
     */
    private Integer codeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_code
     *
     * @mbggenerated
     */
    public OrderCode(Integer id, Integer orderId, Integer codeId) {
        this.id = id;
        this.orderId = orderId;
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_code
     *
     * @mbggenerated
     */
    public OrderCode() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_code.id
     *
     * @return the value of order_code.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_code.id
     *
     * @param id the value for order_code.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_code.order_id
     *
     * @return the value of order_code.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_code.order_id
     *
     * @param orderId the value for order_code.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_code.code_id
     *
     * @return the value of order_code.code_id
     *
     * @mbggenerated
     */
    public Integer getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_code.code_id
     *
     * @param codeId the value for order_code.code_id
     *
     * @mbggenerated
     */
    public void setCodeId(Integer codeId) {
        this.codeId = codeId;
    }
}