package com.jundger.work.pojo;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.cust_id
     *
     * @mbggenerated
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.resolve_status
     *
     * @mbggenerated
     */
    private String resolveStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.resolver_id
     *
     * @mbggenerated
     */
    private Integer resolverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.resolver_name
     *
     * @mbggenerated
     */
    private String resolverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_fee
     *
     * @mbggenerated
     */
    private String totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.describe
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_status
     *
     * @mbggenerated
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.comment_status
     *
     * @mbggenerated
     */
    private String commentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.other
     *
     * @mbggenerated
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public Order(Integer id, Integer custId, String date, String resolveStatus, Integer resolverId, String resolverName, String totalFee, String describe, String payStatus, String commentStatus, Date updateTime, String other) {
        this.id = id;
        this.custId = custId;
        this.date = date;
        this.resolveStatus = resolveStatus;
        this.resolverId = resolverId;
        this.resolverName = resolverName;
        this.totalFee = totalFee;
        this.describe = describe;
        this.payStatus = payStatus;
        this.commentStatus = commentStatus;
        this.updateTime = updateTime;
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public Order() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.cust_id
     *
     * @return the value of order.cust_id
     *
     * @mbggenerated
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.cust_id
     *
     * @param custId the value for order.cust_id
     *
     * @mbggenerated
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.date
     *
     * @return the value of order.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.date
     *
     * @param date the value for order.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.resolve_status
     *
     * @return the value of order.resolve_status
     *
     * @mbggenerated
     */
    public String getResolveStatus() {
        return resolveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.resolve_status
     *
     * @param resolveStatus the value for order.resolve_status
     *
     * @mbggenerated
     */
    public void setResolveStatus(String resolveStatus) {
        this.resolveStatus = resolveStatus == null ? null : resolveStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.resolver_id
     *
     * @return the value of order.resolver_id
     *
     * @mbggenerated
     */
    public Integer getResolverId() {
        return resolverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.resolver_id
     *
     * @param resolverId the value for order.resolver_id
     *
     * @mbggenerated
     */
    public void setResolverId(Integer resolverId) {
        this.resolverId = resolverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.resolver_name
     *
     * @return the value of order.resolver_name
     *
     * @mbggenerated
     */
    public String getResolverName() {
        return resolverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.resolver_name
     *
     * @param resolverName the value for order.resolver_name
     *
     * @mbggenerated
     */
    public void setResolverName(String resolverName) {
        this.resolverName = resolverName == null ? null : resolverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_fee
     *
     * @return the value of order.total_fee
     *
     * @mbggenerated
     */
    public String getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_fee
     *
     * @param totalFee the value for order.total_fee
     *
     * @mbggenerated
     */
    public void setTotalFee(String totalFee) {
        this.totalFee = totalFee == null ? null : totalFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.describe
     *
     * @return the value of order.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.describe
     *
     * @param describe the value for order.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_status
     *
     * @return the value of order.pay_status
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_status
     *
     * @param payStatus the value for order.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.comment_status
     *
     * @return the value of order.comment_status
     *
     * @mbggenerated
     */
    public String getCommentStatus() {
        return commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.comment_status
     *
     * @param commentStatus the value for order.comment_status
     *
     * @mbggenerated
     */
    public void setCommentStatus(String commentStatus) {
        this.commentStatus = commentStatus == null ? null : commentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_time
     *
     * @return the value of order.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_time
     *
     * @param updateTime the value for order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.other
     *
     * @return the value of order.other
     *
     * @mbggenerated
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.other
     *
     * @param other the value for order.other
     *
     * @mbggenerated
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}