package com.jundger.work.pojo;

import java.util.Date;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.cust_id
     *
     * @mbggenerated
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.resolver_id
     *
     * @mbggenerated
     */
    private Integer resolverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.resolver
     *
     * @mbggenerated
     */
    private String resolver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.fee
     *
     * @mbggenerated
     */
    private String fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.describe
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.other
     *
     * @mbggenerated
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated
     */
    public Record(Integer id, Integer custId, String date, String status, Integer resolverId, String resolver, String fee, String describe, Date updateTime, String other) {
        this.id = id;
        this.custId = custId;
        this.date = date;
        this.status = status;
        this.resolverId = resolverId;
        this.resolver = resolver;
        this.fee = fee;
        this.describe = describe;
        this.updateTime = updateTime;
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated
     */
    public Record() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.cust_id
     *
     * @return the value of record.cust_id
     *
     * @mbggenerated
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.cust_id
     *
     * @param custId the value for record.cust_id
     *
     * @mbggenerated
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.date
     *
     * @return the value of record.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.date
     *
     * @param date the value for record.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.status
     *
     * @return the value of record.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.status
     *
     * @param status the value for record.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.resolver_id
     *
     * @return the value of record.resolver_id
     *
     * @mbggenerated
     */
    public Integer getResolverId() {
        return resolverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.resolver_id
     *
     * @param resolverId the value for record.resolver_id
     *
     * @mbggenerated
     */
    public void setResolverId(Integer resolverId) {
        this.resolverId = resolverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.resolver
     *
     * @return the value of record.resolver
     *
     * @mbggenerated
     */
    public String getResolver() {
        return resolver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.resolver
     *
     * @param resolver the value for record.resolver
     *
     * @mbggenerated
     */
    public void setResolver(String resolver) {
        this.resolver = resolver == null ? null : resolver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.fee
     *
     * @return the value of record.fee
     *
     * @mbggenerated
     */
    public String getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.fee
     *
     * @param fee the value for record.fee
     *
     * @mbggenerated
     */
    public void setFee(String fee) {
        this.fee = fee == null ? null : fee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.describe
     *
     * @return the value of record.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.describe
     *
     * @param describe the value for record.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.update_time
     *
     * @return the value of record.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.update_time
     *
     * @param updateTime the value for record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.other
     *
     * @return the value of record.other
     *
     * @mbggenerated
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.other
     *
     * @param other the value for record.other
     *
     * @mbggenerated
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}