package com.jundger.work.pojo;

public class Site {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.owner_id
     *
     * @mbggenerated
     */
    private Integer ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.describe
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.liked
     *
     * @mbggenerated
     */
    private Integer liked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.longitude
     *
     * @mbggenerated
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.latitude
     *
     * @mbggenerated
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.property
     *
     * @mbggenerated
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated
     */
    public Site(Integer id, String name, Integer ownerId, String address, String describe, Integer liked, Float longitude, Float latitude, String picture, String property, String detail) {
        this.id = id;
        this.name = name;
        this.ownerId = ownerId;
        this.address = address;
        this.describe = describe;
        this.liked = liked;
        this.longitude = longitude;
        this.latitude = latitude;
        this.picture = picture;
        this.property = property;
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated
     */
    public Site() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.id
     *
     * @return the value of site.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.id
     *
     * @param id the value for site.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.name
     *
     * @return the value of site.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.name
     *
     * @param name the value for site.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.owner_id
     *
     * @return the value of site.owner_id
     *
     * @mbggenerated
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.owner_id
     *
     * @param ownerId the value for site.owner_id
     *
     * @mbggenerated
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.address
     *
     * @return the value of site.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.address
     *
     * @param address the value for site.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.describe
     *
     * @return the value of site.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.describe
     *
     * @param describe the value for site.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.liked
     *
     * @return the value of site.liked
     *
     * @mbggenerated
     */
    public Integer getLiked() {
        return liked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.liked
     *
     * @param liked the value for site.liked
     *
     * @mbggenerated
     */
    public void setLiked(Integer liked) {
        this.liked = liked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.longitude
     *
     * @return the value of site.longitude
     *
     * @mbggenerated
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.longitude
     *
     * @param longitude the value for site.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.latitude
     *
     * @return the value of site.latitude
     *
     * @mbggenerated
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.latitude
     *
     * @param latitude the value for site.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.picture
     *
     * @return the value of site.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.picture
     *
     * @param picture the value for site.picture
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.property
     *
     * @return the value of site.property
     *
     * @mbggenerated
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.property
     *
     * @param property the value for site.property
     *
     * @mbggenerated
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.detail
     *
     * @return the value of site.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.detail
     *
     * @param detail the value for site.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    @Override
    public String toString() {
        return "Site{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", ownerId=" + ownerId +
                ", address='" + address + '\'' +
                ", describe='" + describe + '\'' +
                ", liked=" + liked +
                ", longitude=" + longitude +
                ", latitude=" + latitude +
                ", picture='" + picture + '\'' +
                ", property='" + property + '\'' +
                ", detail='" + detail + '\'' +
                '}';
    }
}