package com.jundger.carservice.pojo;

public class FaultCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault_code.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault_code.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault_code.system
     *
     * @mbggenerated
     */
    private String system;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault_code.scope
     *
     * @mbggenerated
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault_code.describe
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault_code.other
     *
     * @mbggenerated
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fault_code
     *
     * @mbggenerated
     */
    public FaultCode(Integer id, String code, String system, String scope, String describe, String other) {
        this.id = id;
        this.code = code;
        this.system = system;
        this.scope = scope;
        this.describe = describe;
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fault_code
     *
     * @mbggenerated
     */
    public FaultCode() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault_code.id
     *
     * @return the value of fault_code.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault_code.id
     *
     * @param id the value for fault_code.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault_code.code
     *
     * @return the value of fault_code.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault_code.code
     *
     * @param code the value for fault_code.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault_code.system
     *
     * @return the value of fault_code.system
     *
     * @mbggenerated
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault_code.system
     *
     * @param system the value for fault_code.system
     *
     * @mbggenerated
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault_code.scope
     *
     * @return the value of fault_code.scope
     *
     * @mbggenerated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault_code.scope
     *
     * @param scope the value for fault_code.scope
     *
     * @mbggenerated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault_code.describe
     *
     * @return the value of fault_code.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault_code.describe
     *
     * @param describe the value for fault_code.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault_code.other
     *
     * @return the value of fault_code.other
     *
     * @mbggenerated
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault_code.other
     *
     * @param other the value for fault_code.other
     *
     * @mbggenerated
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}