package com.jundger.work.dao;

import com.jundger.work.pojo.OrderNotify;

import java.util.List;

public interface OrderNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_notify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_notify
     *
     * @mbggenerated
     */
    int insert(OrderNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_notify
     *
     * @mbggenerated
     */
    int insertSelective(OrderNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_notify
     *
     * @mbggenerated
     */
    OrderNotify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderNotify record);

    /**
     * 一次性插入多条数据
     * @param list 数据集合
     * @return
     */
    int insertList(List<OrderNotify> list);

    int updateByOrderNoSelective(OrderNotify record);
}