package com.jundger.work.dao;

import com.jundger.work.pojo.RecordCode;

public interface RecordCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_code
     *
     * @mbggenerated
     */
    int insert(RecordCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_code
     *
     * @mbggenerated
     */
    int insertSelective(RecordCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_code
     *
     * @mbggenerated
     */
    RecordCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RecordCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RecordCode record);
}